### ISSUE TITLE
Incorrect Multisense SL URDF (incorrect transforms and joint types and heirarchy)

### ISSUE THREAD

**Issue by stevenjj** [carnegierobotics/multisense_ros#32]
Hi there, 
I'm not sure when the mistake happened, but I I believe the current multisense SL URDF is incorrect

I don't think the hokuyo's motor frame is should be the child of the left camera optical frame nor should the camera optical link have a continuous joint

https://github.com/carnegierobotics/multisense_ros/blob/6d270058f8caa52b3fdea4f42a9cd7b7af624c7c/multisense_description/urdf/multisenseSL/multisenseSL.urdf.xacro#L24

This is the tf tree after running  view_frames
```
rosrun tf2_tools view_frames.py
 ```
![multisense_sl_incorrect_tree](https://user-images.githubusercontent.com/3218295/144669424-16335eab-a4e4-4900-8aa3-3b57186d8688.png)

Visualizing in Rviz, the hokuyo motor frame is located as the child of the left optical frame. And changing the motor joint spins the hokuyo about this incorrect axis.

![multisenseSL_incorrect_urdf](https://user-images.githubusercontent.com/3218295/144669458-639e91ba-0f13-4fe2-8cde-56d913a579f6.png)

you can reproduce this visualization with the following launch file
````
<launch>
  <param name="robot_description"
          command="$(find xacro)/xacro '$(find multisense_description)/urdf/multisenseSL/standalone.urdf.xacro' name:=multisenseSL"/>

  <!-- send fake joint values -->
  <arg name="use_gui" default="true" doc="Should the joint_state_publisher use a GUI for controlling joint states" />
  <node pkg="joint_state_publisher" type="joint_state_publisher" name="joint_state_publisher" output="screen" unless="$(arg use_gui)" />
  <node pkg="joint_state_publisher_gui" type="joint_state_publisher_gui" name="joint_state_publisher_gui" output="screen" if="$(arg use_gui)" />

  <node name="robot_state_publisher" pkg="robot_state_publisher" type="robot_state_publisher">
    <param name="publish_frequency" value="50" />
  </node>

  <node name="rviz" pkg="rviz" type="rviz"/>

</launch>
````
Then in Rviz Change the frame to multisenseSL/head and add a RobotModel and add TF to view the multisense SL model with frame visualization. 

You may also  have to install the joint state publisher gui package (noetic in this case):
````
sudo apt-get install ros-noetic-joint-state-publisher-gui
````

**Comment by mattalvarado** [comment]
Hi @stevenjj, thanks for reporting this issue. Are you running the driver from the tip of the master branch, or the driver published via the ROS apt packages? I believe the transform tree is correct, but I may have introduced a bug during the tf publishing refactor. You can find a brief write-up on the laser calibration here https://carnegierobotics.com/developer-resources/multisense-sl-transform-tree/.

The transforms from the laser to the spindle and the motor to the left_camera_optical frame both dynamically published after they are queried from the MultiSense SL calibration since they vary between units. Since this is done after the URDF is loaded, I believe the corresponding joints need to be marked as dynamic. The angle of the spindle relative to the motor is published along side the laser data when it is transmitted from the SL. Internally the SL has a absolute encoder which is used to stamp the beginning and end of the laser scan using the Hokuyo sync pulse. On startup the laser needs to be rotated at most 360 degrees for the absolute encoder to find its origin position to properly initialize. This means, to properly publish the transform between the spindle and the motor frames, you need to have a active subscription to the MultiSense SL laser data, and either manually or electronically rotate the spindle 360 degrees after startup. 

Can you try starting a active laser subscription, and start the motor spinning? I believe that will start publishing joint positions between the spindle and the laser, and will hopefully properly complete the transform tree. If that does not resolve the problem, I can take a look when I get back into the office on Monday.

**Comment by stevenjj** [comment]
Hi @mattalvarado thanks for the prompt reply! I think you may have answered my confusion:

> The transforms from the laser to the spindle and the motor to the left_camera_optical frame both dynamically published after they are queried from the MultiSense SL calibration since they vary between units. Since this is done after the URDF is loaded, I believe the corresponding joints need to be marked as dynamic. The angle of the spindle relative to the motor is published along side the laser data when it is transmitted from the SL. 

To answer your question, we use the latest debian release which is 4.0.5, and when using the multisense_bringup launcher and having the hokuyo spin, the transforms are published correctly. 

Given that these joints are intended to be dynamic due to unit calibration, it makes sense that the TF would not be available when the system is powered off. Also, I believe the transform that I'm looking for our particular unit is referenced as **cameraToSpindleFixed** according to the linked page (https://carnegierobotics.com/developer-resources/multisense-sl-transform-tree/)

Thank you! This is issue is closed.
